CREATE DATABASE QUANLYDUAN1
GO 
USE QUANLYDUAN1
GO

CREATE TABLE KHACHHANG
(
	MAKH CHAR(4),
	HOTEN	NVARCHAR(25),
	DCHI	NVARCHAR(25),
	SODT	NUMERIC(20),
	NGSINH	DATETIME,
	DOANHSO	NVARCHAR(25),
	NGDK	DATE,

)	

CREATE	TABLE NHANVIEN
(
	MANV	CHAR(9),
	HOTEN	NVARCHAR(25),
	NGVL	DATETIME,
	SODT	NUMERIC(20),
)

CREATE	TABLE SANPHAM
(
	MASP	CHAR(4),
	TENSP	NVARCHAR(25),
	DVT		NVARCHAR(25),
	NUOCSX	NVARCHAR(25),
	GIA		MONEY,
)

CREATE TABLE HOADON
(
	SOHD	INT,
	NGHD	DATETIME,
	MAKH	CHAR(4),
	MANV	CHAR(9),
	TRIGIA	MONEY,
)
CREATE TABLE  CTHD
(
	SOHD	INT,
	MASP	CHAR(4),
	SL		INT,
)

--------------------------------

ALTER TABLE KHACHHANG
ALTER COLUMN MAKH CHAR(4) NOT NULL

ALTER TABLE KHACHHANG
ADD CONSTRAINT PR_KHACHHANG
PRIMARY KEY (MAKH)

ALTER TABLE NHANVIEN
ALTER COLUMN MANV CHAR(9) NOT NULL

ALTER TABLE NHANVIEN
ADD CONSTRAINT	PR_NHANVIEN
PRIMARY KEY (MANV)

ALTER TABLE SANPHAM
ALTER COLUMN MASP CHAR(4) NOT NULL

ALTER TABLE SANPHAM
ADD CONSTRAINT PR_SANPHAM
PRIMARY KEY (MASP)

ALTER TABLE HOADON
ALTER COLUMN SOHD INT NOT NULL

ALTER TABLE HOADON
ADD CONSTRAINT PR_HOADON
PRIMARY KEY (SOHD)

ALTER TABLE CTHD
ALTER COLUMN SOHD INT NOT NULL

ALTER TABLE CTHD 
ALTER COLUMN MASP CHAR(4) NOT NULL

ALTER TABLE CTHD
ADD CONSTRAINT PR_CTHD
PRIMARY KEY ( SOHD,MASP)

ALTER TABLE HOADON ADD  CONSTRAINT FK_MAKH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
ALTER TABLE HOADON ADD CONSTRAINT FK_MANV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
ALTER TABLE CTHD ADD CONSTRAINT FK_SOHD FOREIGN KEY (SOHD) REFERENCES HOADON(SOHD)
ALTER TABLE CTHD ADD CONSTRAINT FK_MASP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)

------------------------LAM BAI---------
ALTER TABLE SANPHAM
ADD	GHICHU VARCHAR(20)

ALTER TABLE SANPHAM 
ALTER COLUMN GHICHU VARCHAR(100)

ALTER TABLE KHACHHANG
ADD LOAIKH VARCHAR(20)

ALTER TABLE KHACHHANG
ADD CONSTRAINT CK_KHACHHANG_LOAIKH
CHECK(LOAIKH IN('Vang lai', 'Thuong xuyen', 'Vip'))

ALTER TABLE SANPHAM
ADD CONSTRAINT CK_SANPHAM_DVT
CHECK(DVT IN('cay', 'hop', 'cai', 'quyen', 'chuc'))

ALTER TABLE SANPHAM
ADD CONSTRAINT CK_SANPHAM_GIA
CHECK (GIA>=500)

ALTER TABLE KHACHHANG
ADD CONSTRAINT CK_KHACHHANG_NGDK
CHECK(NGDK>NGSINH)


